<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRpjVFbs\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRpjVFbs/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRpjVFbs.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRpjVFbs\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRpjVFbs\App_KernelProdContainer([
    'container.build_hash' => 'RpjVFbs',
    'container.build_id' => 'f017fe73',
    'container.build_time' => 1626693188,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRpjVFbs');
