<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'test1' => [[], ['_controller' => 'App\\Controller\\TestOneController::rangeOfTheLoop'], [], [['text', '/test1']], [], []],
    'test3' => [[], ['_controller' => 'App\\Controller\\TestThreeController::index'], [], [['text', '/test3']], [], []],
    'test2' => [['num'], ['5', '_controller' => 'App\\Controller\\TestTwoController::index'], [], [['variable', '', '[^/]++', 'num', true], ['text', '/test2']], [], []],
    'api_fibonacci' => [['num'], ['_controller' => 'App\\Controller\\TestTwoController::index'], [], [['variable', '/', '[^/]++', 'num', true], ['text', '/test2']], [], []],
];
