<?php

namespace ContainerDhk7NBO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFizzBuzzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\FizzBuzz' shared autowired service.
     *
     * @return \App\Security\FizzBuzz
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/FizzBuzz.php';

        return $container->privates['App\\Security\\FizzBuzz'] = new \App\Security\FizzBuzz();
    }
}
